In [31]:
from astropy.cosmology import FlatLambdaCDM
import numpy as np
from scipy.integrate import quad

/home/gqzhang/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/gqzhang/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
data = np.loadtxt('data/C11.csv', delimiter=',')

In [4]:
data[:,0]

array([0.50349, 0.4952 , 0.6782 , ..., 1.014  , 1.315  , 1.092  ])

In [6]:
cosmo = FlatLambdaCDM(H0=70, Om0 = 0.3)

In [8]:
length = cosmo.luminosity_distance(data[:, 0])

In [11]:
uth = 5 * np.log10(length.value) + 25

In [12]:
A = ((uth - data[:, 1]) ** 2 / data[:,2]).sum()

In [13]:
A

149.91787444475813

In [16]:
uth[-2]

44.835882460703445

In [15]:
 data[:, 1][-1]

43.9397

In [17]:
data[:,2]

array([0.1337, 0.118 , 0.2142, ..., 0.2433, 0.2001, 0.28  ])

In [23]:
cosmo.luminosity_distance(1e-5) * 70 / 3e5 / (1 + 1e-5)

<Quantity 9.99305945e-06 Mpc>

In [25]:
data[:, 0][-1]

1.092

In [26]:
data[:, 0][-2]

1.315

In [28]:
data[:, 0][-10:]

array([1.37  , 0.9752, 0.97  , 0.74  , 1.39  , 1.305 , 0.935 , 1.014 ,
       1.315 , 1.092 ])

In [29]:
def E(z):
    return 1 / np.sqrt(0.7 + 0.3 * (1 + z) ** 3)

In [42]:
tg = []
for i in data[:, 0]:
    tg.append(quad(E, 0, i)[0])

In [57]:
cosmo.luminosity_distance(1) 

<Quantity 6607.65761177 Mpc>

In [58]:
quad(E, 0, 1)[0] / 70 * 2 * 2.997e5

6605.619765954714

In [46]:
tg = np.array(tg)

In [52]:
uth = 5 * np.log10(test / 70) + 25

In [53]:
uth

array([39.90526544, 39.83797203, 41.09699266, ..., 42.64895831,
       43.60925901, 42.92642117])

In [56]:
((uth - data[:, 1]) ** 2 / data[:, 2] ** 2).sum()

1225451.1677925792